"""add crm fields

Revision ID: 4a658dc6812d
Revises: 427771847131
Create Date: 2026-04-20 14:09:10.308310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a658dc6812d'
down_revision: Union[str, Sequence[str], None] = '427771847131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('internal_status', sa.String(), nullable=True))
    op.alter_column('platform_tokens', 'account_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('posts', 'platform_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'platform_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('platform_tokens', 'account_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('clients', 'internal_status')
    op.drop_column('clients', 'notes')
    op.drop_column('clients', 'contact_email')
    op.drop_column('clients', 'industry')
    # ### end Alembic commands ###
